name: flutter_app_template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.9
  multi_async_value: ^0.0.1
  go_router: ^13.0.1
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0
  image_picker: ^1.0.7
  path: ^1.8.3
  flutter_image_compress: ^2.1.0
  exif: ^3.3.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  theme_tailor: ^2.1.0
  theme_tailor_annotation: ^2.1.0
  intl: ^0.17.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  cider: ^0.2.5
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7
  go_router_builder: ^2.4.1
  widgetbook_generator: ^3.7.0
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true
